---
:backgroundrb:
  :ip: 0.0.0.0
  :port: 11006
  :environment: development
  :log: foreground # logs messages on the console
  :persistent_delay: 10  # the time (seconds) between each time backgroundrb checks the database for enqueued tasks
  
  
# from: http://backgroundrb.rubyforge.org/